apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web
  params:
    - default: main
      name: gitops_branch
    - default: supplychain
      name: gitops_user_name
    - default: supplychain
      name: gitops_user_email
    - default: supplychain@cluster.local
      name: gitops_commit_message
    - default: ""
      name: gitops_ssh_secret
    - default: share-controller-sa
      name: serviceAccount
  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source-template
    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
      params:
        - name: image_prefix
          default: test
        - name: builder_name
          default: java-builder
      sources:
        - name: source
          resource: source-provider
    - name: config-provider
      images:
        - resource: image-builder
          name: image
      templateRef:
        kind: ClusterConfigTemplate
        name: convention-template
    - name: app-config
      images:
        - resource: image-builder
          name: image
      configs:
        - name: config
          resource: config-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: app-config
    - name: config-writer
      templateRef:
        kind: ClusterTemplate
        name: config-writer-template
      configs:
        - resource: app-config
          name:  config
