apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: java-source-1
  namespace: demons
  labels:
    app.tanzu.vmware.com/workload-type: web
spec:
  serviceAccountName: demo-sa
  source:
    git:
      url: https://github.com/yilims/java-native.git
      ref:
        branch: azure
  builder:
    name: sample-builder
    kind: ClusterBuilder
  cache:
    volume:
      size: "1.5Gi"
  successBuildHistoryLimit: 10
  failedBuildHistoryLimit: 10
  params:
    - name: image_prefix
      value: demoacr.azurecr.io/demo-repo/cartographer-demons
    - name: builder_name
      default: java-builder
  build:
    env:
      - name: BP_MAVEN_BUILD_ARGUMENTS
        value: "-Dmaven.test.skip=true package"
    resources:
      requests:
      limits:
        cpu: "0.5"
        memory: "1Gi"
